apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-payment-gateway-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.6"
  ACCOUNT_ID: "aws:908671954593"
  POD_NAME: "go-payment-gateway.eks-arch-01"
  PORT: "6004"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "80"
  CTX_TIMEOUT: "5"
  SETPOD_AZ: "false"
  ENV: "dev"

  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "SASL_SSL"
  KAFKA_MECHANISM: "SCRAM-SHA-512"
  KAFKA_CLIENT_ID: "GO-PAYMENT-GATEWAY-01"
  KAFKA_BROKER_1: "b-1.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_2: "b-2.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_3: "b-3.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "2"
  TOPIC_PIX: "topic.pix.01"
  TOPIC_WEBHOOK_PIX: "topic.webhook.pix.01"

  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
  USE_STDOUT_TRACER_EXPORTER: "false"
  USE_OTLP_COLLECTOR: "true" 
  AWS_CLOUDWATCH_LOG_GROUP_NAMES: "/dock/eks/eks-arch-01"

  NAME_SERVICE_00: "go-account"
  URL_SERVICE_00: "https://nlb-eks-arch-01.architecture.caradhras.io" 
  METHOD_SERVICE_00: "GET"
  HOST_SERVICE_00: "go-account.architecture.caradhras.io"
  CLIENT_HTTP_TIMEOUT_00: "5"
  
  #X_APIGW_API_ID_SERVICE_00: "129t4y8eoj"
  #URL_SERVICE_00: "https://vpce.global.dev.caradhras.io/pv"

  NAME_SERVICE_01: "go-limit"
  URL_SERVICE_01: "https://nlb-eks-arch-02.architecturedev.caradhras.io" #https://vpce.global.dev.caradhras.io/pv
  METHOD_SERVICE_01: "POST"
  HOST_SERVICE_01: "go-limit.architecturedev.caradhras.io"
  CLIENT_HTTP_TIMEOUT_01: "5"

  NAME_SERVICE_02: "go-ledger"
  URL_SERVICE_02: "https://nlb-eks-arch-01.architecture.caradhras.io" 
  METHOD_SERVICE_02: "POST"
  HOST_SERVICE_02: "go-ledger.architecture.caradhras.io"
  CLIENT_HTTP_TIMEOUT_02: "5"

  NAME_SERVICE_03: "go-card"
  URL_SERVICE_03: "https://nlb-eks-arch-02.architecturedev.caradhras.io" 
  METHOD_SERVICE_03: "GET"
  HOST_SERVICE_03: "go-card.architecturedev.caradhras.io"
  CLIENT_HTTP_TIMEOUT_03: "5"

  NAME_SERVICE_04: "go-card"
  URL_SERVICE_04: "https://nlb-eks-arch-02.architecturedev.caradhras.io" 
  METHOD_SERVICE_04: "POST"
  HOST_SERVICE_04: "go-card.architecturedev.caradhras.io"
  CLIENT_HTTP_TIMEOUT_04: "5"